### ISSUE TITLE
MergeError: coordinate point_id shares a name with a dataset dimension ….

### ISSUE THREAD

**Issue by joelfiddes** [ArcticSnow/TopoPyScale#40]
l.74 solar_geom.py   

running "swat" sim (points in Karakorum)

Same issue as this:
https://github.com/pydata/xarray/issues/2931
        
solved as suggested:
` "point_id": df_position.index),`
to 
`"point_id":(("point_id"), df_position.index),`

But why?! Have not seen in map jobs.

**Comment by ArcticSnow** [comment]
Is this still a bug? I do not recall having prob here.
