### ISSUE TITLE
Precipitation totals wrong at timesteps higher than 1h

### ISSUE THREAD

**Issue by joelfiddes** [ArcticSnow/TopoPyScale#41]
precip in era5 is still hourly sums (m) even at timesteps more than 1h - we are just simply missing precip budget. eg 6h data could be:

0, 0, 0.002, 0.002 (m)

this doesnt mean daily sum of 0.004m but more likely 0.004*4 = 0.016m

here is the bug in topo_scale.py:

down_pt['tp'] = surf_interp.tp  * 1 / tstep_dict.get(tstep) * 10**3 # Convert to mm/hr

do not divide by timestep.

Furthermore, a rough way to get the budget right is to multiply by timestep.

Current code produces precip budgets around 9 times too low for a 3h timestep - twice an error of factor three.

**Comment by ArcticSnow** [comment]
Let's open an issue about adding support for other timestep resolution

**Comment by ArcticSnow** [comment]
See issue #104
