### ISSUE TITLE
MASSIVE bug in downscaling

### ISSUE THREAD

**Issue by ArcticSnow** [ArcticSnow/TopoPyScale#60]
With the latest commit ([988a7b2](https://github.com/ArcticSnow/TopoPyScale/commit/988a7b2d98fc638ac955121afa25a4ececd4047e)) the outputs are totally off, full of noise and incoherent in time. The same output are fine with commit e30c720.

This is the unwanted output for LW
![image](https://user-images.githubusercontent.com/2042458/223163584-694324db-f2b8-4f35-9ee2-015649a985a1.png)

This is correct downscaling of LW for instance:
![image](https://user-images.githubusercontent.com/2042458/223163024-c1962c5c-d7b8-4a02-a019-b253546db519.png)

**Comment by ArcticSnow** [comment]
This unwanted behavior has been introduced at merge with the branch `parallelizing` at commit 51d2d08

**Comment by ArcticSnow** [comment]
I nailed where the problem is introduced. It happens within the function `_subset_climate_dataset()`.
https://github.com/ArcticSnow/TopoPyScale/blob/6a4c68e9a0e2f9f1c66427924e75d8c126fbd963/TopoPyScale/topo_scale.py#L182

**Comment by ArcticSnow** [comment]
The problem is introduced when saving temporary dataset to disk with  `ds_tmp.to_netcdf(f'outputs/tmp/ds_{type}_pt_{pt_id}.nc', engine='h5netcdf')`

**Comment by ArcticSnow** [comment]
Not the first one to run into this problem: https://github.com/pydata/xarray/issues/7039

This seems to be related to how ERA5 data are encoded in netcdf. Then we need to force encoding with saving to netcdf with the following lines:

```python
comp = dict(zlib=True, complevel=5)
encoding = {var: comp for var in ds_tmp.data_vars}
ds_tmp.to_netcdf(f'outputs/tmp/ds_{type}_pt_{pt_id}.nc', engine='h5netcdf', encoding=encoding)
```

This was found on stackoverflow: https://stackoverflow.com/questions/40766037/specify-encoding-compression-for-many-variables-in-xarray-dataset-when-write-to

**Comment by veenstrajelmer** [comment]
@ArcticSnow. A more desireable solution might be to remove the `dtype` or `scale_factor` key from the encoding dict. See also my answer in the stackoverflow issue: https://stackoverflow.com/a/75665502/5578371

**Comment by ArcticSnow** [comment]
Thank you for your suggestion @veenstrajelmer. I actually had read your comment on stackoverflow but came short of figuring out how to actually do it. If you have concrete suggestion it could be interesting. The other thing is that compressing the file stored is improved disk space usage. Or the technique may be to compute a new offset and convert all variable to INT. I have a method in place but not yet optimal see: https://github.com/ArcticSnow/TopoPyScale/blob/494f4e7ea17830ba3d23627bf22ee200a6c4f082/TopoPyScale/topo_export.py#L21. 

Any suggestions on how to improve this is also welcome. Thank you

**Comment by veenstrajelmer** [comment]
That is a great suggestion. I have tested your implementation and it works quite ok. The only thing I notice is that the offset seems to be off by `scale_factor/2`. However, I have not succeeded in resolving this. I have tried `add_offset =  (vmax+vmin) / 2` (which is the same as `vmin + 2 ** (n - 1) * scale_factor -scale_factor/2`). This does give a slightly different `add_offset` value, but does not resolve the offset that I am seeing. I have tested it with u10 and mslp variables. The noise is within expected accuracy range I expect, but I do not understand why the mean of the plots is not 0. Did you experience the same?

![image](https://user-images.githubusercontent.com/60435591/223701906-ac346b9f-90bd-47ac-9939-d69f1c7c9f4a.png)

![image](https://user-images.githubusercontent.com/60435591/223701951-15b0c4c1-9dad-49d9-a61c-c6709c86e84a.png)

**Comment by ArcticSnow** [comment]
Nice! I think I will reuse your function with another evolution. ;)

I suspect improvements is possible as when I zip the netcdfs out of this encoding, `zip` is able to deflate the files by up to 56%.  Maybe using `int8` instead of `int16` was it.

FYI, I had found the idea and original implementation here: https://stackoverflow.com/questions/70102997/scale-factor-and-add-offset-in-xarray-to-netcdf-lead-to-some-small-negative-valu

**Comment by veenstrajelmer** [comment]
Hmm, maybe it is indeed easier to zip it. This gives the same filesize and is somewhat easier to implement I guess. Here only for the msl variable, but you get the point.
```
ds.msl.encoding.pop('dtype')
ds.msl.encoding.pop('scale_factor')
ds.msl.encoding.pop('add_offset')
ds.msl.encoding['zlib'] = True
```
