### ISSUE TITLE
How to plotting downscaled results?

### ISSUE THREAD

**Issue by NILICK** [ArcticSnow/TopoPyScale#64]
I could run the example2 successfully, and the model produced `nc` files in the outputs folder. I want to show the temperature downscaled in GIS environment such as QGIS, but I confused to do that because in QGIS the output files not readable and return below error:

`Unsupported Data Source: /TopoPyScale/Examples/TopoPyScale_examples-main/ex2_romania_retezat/outputs/downscaled/down_pt_2.nc is not a supported raster data source This raster file has no bands and is invalid as a raster layer.`
How can I plot the downscaled result as a map such as [this](https://github.com/ArcticSnow/TopoPyScale/blob/main/JOSS/temperature_comparison_crop_scaled.jpg).

**Comment by ArcticSnow** [comment]
See the documentation page [Exampels](https://topopyscale.readthedocs.io/en/latest/6_examples/)
This will plot the timeseries of each clustered mapped to the corresponding DEM pixels. 

```python
mp.plot.map_variable(time_step=1, var='t')

import matplotlib.pyplot as plt
plt.show()
```

**Comment by ArcticSnow** [comment]
Look here: https://github.com/ArcticSnow/TopoPyScale/blob/a723a6c3bcadb40f7003abd026e891c51c046ac1/TopoPyScale/topo_plot.py#L95
