### ISSUE TITLE
errors in to_fsm2oshd

### ISSUE THREAD

**Issue by paswyss** [ArcticSnow/TopoPyScale#94]
There are some issues with the to_fsm2oshd  function (e.g. a lot of unused parameters, wrongly named parameters like fsm_mode instead of mode) etc.
This would make the whole topopyscale not work. Since I wasn't able to quick fix (and I didn't now what your goal of the function is), I outcommented the funciton for not, so the topopyscale still works.

**Comment by ArcticSnow** [comment]
Well done @paswyss . Sorry for that. 
I later continued dev on a branch to avoid problems. When working I'll merge the two with heads up.
